vaadin.launch-browser=true
vaadin.copilot.enable=false
spring.application.name=unternehmensstruktur

# PostgreSQL Datenbank
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/unternehmenshierarchie}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=unternehmensstruktur

server.port=8080
